
a = Analysis(['main.py'],
             pathex=[],
             binaries=[('<path-to-openvino-package-in-env>\\libs\\*', '.\\openvino\\libs')],
             datas=[('<path-to-music_source_separation-model>\\*', '.\\music_source_separation\\model'),
			        ('<path-to-librosa-package-in-env>\\util\\example_data\\*', '.\\librosa\\util\\example_data'),
					('<path-to-music_transcription-model>\\basic_pitch_43844_model.onnx', '.\\music_transcription')],
             hiddenimports=['openvino.pyopenvino', 'openvino.inference_engine.constants'],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='CyberAudio',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=True,
          version='',
          icon='')
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               upx_exclude=[],
               name='CyberAudio')